### ISSUE TITLE
F-Droid.org

### ISSUE THREAD

**Issue by BoBeR182** [scottyab/safetynethelper#32]
Will the app be added to https://f-droid.org

**Comment by scottyab** [comment]
I'm all for it, but I thought that to be in F-droid there could be no dependancy on Google Play services? - i might be wrong

**Comment by IzzySoft** [comment]
Yes, those would be a show-stopper – which is why the app is currently in my repo. Still wondering whether you're still maintaining it? Got a bit calm here, @scottyab :wink:

**Comment by scottyab** [comment]
For clarity no plans to add to f-droid.org thanks for the question

**Comment by IzzySoft** [comment]
Thanks for your reply, @scottyab! With the last release almost 3 years in the past (2/2017), and the last commit more than a year ago, the question from my end was rather whether you still maintain it (and if there'll be a new release covering the 13 commits since the last one)?

@BoBeR182 can find the app [here in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.scottyab.safetynet.sample) to be used with the F-Droid client. Should @scottyab release a new version, you should be notified by the F-Droid client then.

**Comment by IzzySoft** [comment]
@scottyab could you please attach the APK to the latest release? Looks like you forgot :pray:
