### ISSUE TITLE
Incompatible with safetynet 12.x

### ISSUE THREAD

**Issue by zharf** [scottyab/safetynethelper#37]
SafetyNet API has changed, some class names have changed and there's no need to connect to google api client manually anymore

**Comment by robsmall** [comment]
One thing to note is that you will need an API key for the new API and that it is rate limited to 10,000 requests/day. I believe that in ~90 days the old api calls will no longer work and will get back a networking error.

One cool thing could be to use the JavaPropFile plugin to allow users to provide their own API key so that not everyone's app is using yours and so you don't have to hard-code it into this repo and have an api key in version control.

**Comment by PurplProto** [comment]
This issue has appeared to have struck and thus an update is now needed. There appears to be a PR to add support for this, but it was made months ago and the repo owner appears to be inactive too. 

I guess we'll have to fork this and add it ourselves.

**Comment by scottyab** [comment]
yep thank for flagging this I'm looking into it

**Comment by scottyab** [comment]
resolved, thanks for rasing
